### ISSUE TITLE
Releasing the GIL

### ISSUE THREAD

**Issue by ahirner** [wyfo/pyo3-async#1]
Hi, I like the runtime agnostic approach!

Is it possible to write a `Coroutine` which releases the GIL, then runs some compute in a (scoped) thread? If so, how and if not what part of the API should be touched?

Similarly, I'd like to know how to push results from a GIL released thread into a `asyncio::AsyncGenerator`.

**Comment by wyfo** [comment]
Actually, the default implementation release the GIL when Rust futures are polled https://github.com/wyfo/pyo3-async/blob/9e1b480d4d62b59cedaff376d2d240b9d641c45c/src/lib.rs#L35.

To "push results", I would use a channel like [tokio mpsc](https://docs.rs/tokio/latest/tokio/sync/mpsc/fn.channel.html), and convert the channel receiver into [stream](https://docs.rs/tokio-stream/latest/tokio_stream/wrappers/struct.ReceiverStream.html), which can then be wrapped into `asyncio::AsyncGenerator`.

**Comment by ahirner** [comment]
Amazing that's already taken care of by default. Thanks for pointing to the exact impl!

**Comment by wyfo** [comment]
In the end, releasing the GIL don't seem to be the best default behavior. See #2 where I explain why the behavior will be reverted in the next release.

Of course, I've provided a simple way to release the GIL. I will wait a bit before publishing the next release, if you have some remarks about this decision, don't hesitate to write them.
